// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoCarro.DataAccess.Context;

#nullable disable

namespace SoCarro.DataAccess.Migrations
{
    [DbContext(typeof(SoCarroDbContext))]
    [Migration("20220212150125_TabelasIniciais")]
    partial class TabelasIniciais
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SoCarro.Business.Models.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("ProprietarioId")
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProprietarioId")
                        .IsUnique();

                    b.ToTable("Endereco", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("5c824376-c134-43cf-ac42-5ba1e3a1d9e1"),
                            Bairro = "Centro",
                            Cep = "78098000",
                            Cidade = "Cuiabá",
                            Complemento = "Quadra 15",
                            Estado = "MT",
                            Logradouro = "Rua 10",
                            Numero = "01",
                            ProprietarioId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("9c3fee74-05ae-42ec-b841-88a31c243401"),
                            Bairro = "Porto",
                            Cep = "78098000",
                            Cidade = "Cuiabá",
                            Complemento = "Quadra 36",
                            Estado = "MT",
                            Logradouro = "Rua Brazil",
                            Numero = "10",
                            ProprietarioId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("b397ea69-31cf-48fb-9425-8222a95e1cc4"),
                            Bairro = "Jardim Universitário",
                            Cep = "78098000",
                            Cidade = "Cuiabá",
                            Complemento = "Quadra 98",
                            Estado = "MT",
                            Logradouro = "Rua Orquideas",
                            Numero = "01",
                            ProprietarioId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("6d335490-c849-4792-919e-adb38dd964f2"),
                            Bairro = "Jardim Imperial",
                            Cep = "78098000",
                            Cidade = "Cuiabá",
                            Complemento = "Quadra 70",
                            Estado = "MT",
                            Logradouro = "Rua 42",
                            Numero = "395",
                            ProprietarioId = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("SoCarro.Business.Models.Marca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Marca", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b358b8dd-be36-4afe-8c6b-4ce7438a434a"),
                            DataCadastro = new DateTime(2022, 2, 12, 11, 1, 25, 597, DateTimeKind.Local).AddTicks(2509),
                            Nome = "Volkswagen",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("ef2ae5a0-9b10-4372-a214-79ded3e0f5a3"),
                            DataCadastro = new DateTime(2022, 2, 12, 11, 1, 25, 597, DateTimeKind.Local).AddTicks(2528),
                            Nome = "Toyota",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("1962c218-a0dc-4746-b406-0bd79aa6e5a8"),
                            DataCadastro = new DateTime(2022, 2, 12, 11, 1, 25, 597, DateTimeKind.Local).AddTicks(2529),
                            Nome = "Ford",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("879d7c81-9841-4469-b71d-ecd09ae07fdf"),
                            DataCadastro = new DateTime(2022, 2, 12, 11, 1, 25, 597, DateTimeKind.Local).AddTicks(2531),
                            Nome = "Honda",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("c30375f4-d336-4a5f-af87-f8bd87eabc6e"),
                            DataCadastro = new DateTime(2022, 2, 12, 11, 1, 25, 597, DateTimeKind.Local).AddTicks(2532),
                            Nome = "Hyundai",
                            Status = 0
                        });
                });

            modelBuilder.Entity("SoCarro.Business.Models.Modelo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AnoFabricacao")
                        .HasColumnType("int");

                    b.Property<int>("AnoModelo")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("VeiculoId")
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VeiculoId")
                        .IsUnique();

                    b.ToTable("Modelo", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("489b69d4-5025-4526-a42c-68de204a1b08"),
                            AnoFabricacao = 2020,
                            AnoModelo = 2021,
                            Descricao = "Trend",
                            VeiculoId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("91c37cdb-fb51-4766-a23e-d204af8a9516"),
                            AnoFabricacao = 2021,
                            AnoModelo = 2021,
                            Descricao = "Confort line",
                            VeiculoId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("8d3bc0ee-f683-4f99-af82-c51f7c5d7aef"),
                            AnoFabricacao = 2021,
                            AnoModelo = 2022,
                            Descricao = "Verão",
                            VeiculoId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("e77d018a-ab5e-404a-930a-1e9ee4f3792f"),
                            AnoFabricacao = 2021,
                            AnoModelo = 2022,
                            Descricao = "Inferno",
                            VeiculoId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("5f3c18db-d77f-424c-ba90-58e2de3ab2d9"),
                            AnoFabricacao = 2022,
                            AnoModelo = 2022,
                            Descricao = "Esportivo",
                            VeiculoId = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("SoCarro.Business.Models.Proprietario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(14)
                        .IsUnicode(false)
                        .HasColumnType("varchar(14)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TipoProprietario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Proprietario", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("47c477a8-3063-4df1-be95-1d8919850f40"),
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Documento = "80292613067",
                            Email = "jose@socarro.com.br",
                            Nome = "Zé do Carro",
                            Status = 0,
                            TipoProprietario = 1
                        },
                        new
                        {
                            Id = new Guid("5f535587-ea67-4395-aca1-47261934ac84"),
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Documento = "66689736040",
                            Email = "tonho@socarro.com.br",
                            Nome = "Tonho do Carro",
                            Status = 0,
                            TipoProprietario = 1
                        },
                        new
                        {
                            Id = new Guid("8ccca536-c35e-4eb2-9bdb-7b23f764ad92"),
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Documento = "65695214033",
                            Email = "maria.jose@socarro.com.br",
                            Nome = "Maria José",
                            Status = 0,
                            TipoProprietario = 1
                        },
                        new
                        {
                            Id = new Guid("f499f8c0-15d8-4a79-b66a-35728712dea8"),
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Documento = "66689736040",
                            Email = "jose.maria@socarro.com.br",
                            Nome = "José Maria",
                            Status = 0,
                            TipoProprietario = 1
                        });
                });

            modelBuilder.Entity("SoCarro.Business.Models.Veiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MarcaId")
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("ProprietarioId")
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quilometragem")
                        .HasColumnType("int");

                    b.Property<string>("Renavam")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MarcaId")
                        .IsUnique();

                    b.HasIndex("ProprietarioId")
                        .IsUnique();

                    b.ToTable("Veiculo", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("48ecbd3c-660b-42fb-90f4-38cc33e596ea"),
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MarcaId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Nome = "Gol",
                            ProprietarioId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Quilometragem = 15000,
                            Renavam = "76473056607",
                            Status = 0,
                            Valor = 45000m
                        },
                        new
                        {
                            Id = new Guid("1c667238-fe0e-4c7e-9519-94438d04ce8d"),
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MarcaId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Nome = "Voyage",
                            ProprietarioId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Quilometragem = 50000,
                            Renavam = "74493153016",
                            Status = 0,
                            Valor = 32000m
                        },
                        new
                        {
                            Id = new Guid("50e2c51f-9684-42b2-8bb1-972ee8d22038"),
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MarcaId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Nome = "Corolla",
                            ProprietarioId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Quilometragem = 0,
                            Renavam = "91838212968",
                            Status = 0,
                            Valor = 105000m
                        },
                        new
                        {
                            Id = new Guid("228f3149-61d1-4e7e-96bf-29d27da650df"),
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MarcaId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Nome = "Sandero",
                            ProprietarioId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Quilometragem = 65000,
                            Renavam = "75106570228",
                            Status = 0,
                            Valor = 55000m
                        },
                        new
                        {
                            Id = new Guid("8599fc54-30b3-4b7d-846b-00da02d5e5e1"),
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MarcaId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Nome = "Palio",
                            ProprietarioId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Quilometragem = 118000,
                            Renavam = "83663783642",
                            Status = 0,
                            Valor = 25000m
                        });
                });

            modelBuilder.Entity("SoCarro.Business.Models.Endereco", b =>
                {
                    b.HasOne("SoCarro.Business.Models.Proprietario", "Proprietario")
                        .WithOne("Endereco")
                        .HasForeignKey("SoCarro.Business.Models.Endereco", "ProprietarioId")
                        .IsRequired();

                    b.Navigation("Proprietario");
                });

            modelBuilder.Entity("SoCarro.Business.Models.Modelo", b =>
                {
                    b.HasOne("SoCarro.Business.Models.Veiculo", "Veiculo")
                        .WithOne("Modelo")
                        .HasForeignKey("SoCarro.Business.Models.Modelo", "VeiculoId")
                        .IsRequired();

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("SoCarro.Business.Models.Veiculo", b =>
                {
                    b.HasOne("SoCarro.Business.Models.Marca", "Marca")
                        .WithOne("Veiculo")
                        .HasForeignKey("SoCarro.Business.Models.Veiculo", "MarcaId")
                        .IsRequired();

                    b.HasOne("SoCarro.Business.Models.Proprietario", "Proprietario")
                        .WithOne("Veiculo")
                        .HasForeignKey("SoCarro.Business.Models.Veiculo", "ProprietarioId")
                        .IsRequired();

                    b.Navigation("Marca");

                    b.Navigation("Proprietario");
                });

            modelBuilder.Entity("SoCarro.Business.Models.Marca", b =>
                {
                    b.Navigation("Veiculo")
                        .IsRequired();
                });

            modelBuilder.Entity("SoCarro.Business.Models.Proprietario", b =>
                {
                    b.Navigation("Endereco")
                        .IsRequired();

                    b.Navigation("Veiculo")
                        .IsRequired();
                });

            modelBuilder.Entity("SoCarro.Business.Models.Veiculo", b =>
                {
                    b.Navigation("Modelo")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
